import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  mx-auto flex h-screen  flex-col items-center justify-center gap-2 bg-background bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  );
}
