import { Button } from "$/components/ui/button";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>NextGen form App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  mx-auto flex h-screen  flex-col items-center justify-center gap-2 bg-background ">
        <div className="title center flex flex-col items-center justify-center">
          <h1 className="text-xl font-bold"> There is three types of forms</h1>
          <span className="text-muted-foreground">Please chose one</span>
        </div>
        <div className="flex flex-row gap-2">
          <Button asChild>
            <Link href="/basic-form">Basic Form</Link>
          </Button>
          <Button asChild>
            <Link href="/password-validation">Password Form</Link>
          </Button>
          <Button asChild>
            <Link href="/multi-step">Multi step form</Link>
          </Button>
        </div>
      </main>
    </>
  );
}
